# Generated by Django 6.1.1 on 2026-09-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fruit',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fruit',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
