# Generated by Django 6.1.1 on 2026-09-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_app', '0002_fruit_description_fruit_is_available_fruit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='origin_country',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
