# Generated by Django 6.1.1 on 2026-09-15 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_app', '0004_customer_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='fruit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('fruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fruit_app.fruit')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fruit_app.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='fruits',
            field=models.ManyToManyField(through='fruit_app.OrderItem', to='fruit_app.fruit'),
        ),
    ]
