# Generated by Django 6.1.1 on 2026-09-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_app', '0005_remove_order_fruit_remove_order_quantity_orderitem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fruit',
            options={'ordering': ['name'], 'verbose_name_plural': 'Fruits'},
        ),
        migrations.AddField(
            model_name='fruit',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
